version: "3.8"
services:
  postgres_db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=ksd
