"""Initial migration

Revision ID: a6234024b341
Revises: 
Create Date: 2024-05-28 23:37:39.261944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6234024b341'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key of the category'),
    sa.Column('name', sa.String(), nullable=False, comment='Name of the category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('general_ocrs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key of the general OCR settings'),
    sa.Column('ocr_api_url', sa.String(), nullable=False, comment='URL of the OCR API'),
    sa.Column('ocr_api_key', sa.String(), nullable=False, comment='API key for the OCR service'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_ocrs_id'), 'general_ocrs', ['id'], unique=False)
    op.create_table('category_keywords',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key of the category keyword'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Foreign key referencing the category'),
    sa.Column('keyword', sa.String(), nullable=False, comment='Keyword associated with the category'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_keywords_id'), 'category_keywords', ['id'], unique=False)
    op.create_table('category_ocrs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key of the category OCR settings'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Foreign key referencing the category'),
    sa.Column('ocr_api_url', sa.String(), nullable=False, comment='URL of the OCR API'),
    sa.Column('ocr_api_key', sa.String(), nullable=False, comment='API key for the OCR service'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_ocrs_id'), 'category_ocrs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_ocrs_id'), table_name='category_ocrs')
    op.drop_table('category_ocrs')
    op.drop_index(op.f('ix_category_keywords_id'), table_name='category_keywords')
    op.drop_table('category_keywords')
    op.drop_index(op.f('ix_general_ocrs_id'), table_name='general_ocrs')
    op.drop_table('general_ocrs')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
